#include <stdio.h>
#include <stdlib.h>
#define MAX 81

int main()
{
    char name[MAX]; // allot space
    char ch;

    printf("Hi, what's your name? USING GETS\n");
    gets(name); /* gets() will take all characters input (up to a limit of 80 characters)
                   up to but not including the new line generated by hitting the enter key.
                   The function will, however, tack on a null character '\0' at the end of the line.
                   DOES NOT CHECK IF INPUT FITS IN ALLOCATED MEMORY    */
    printf("Nice name, %s.\n", name);

    char * ptr;

    printf("Hi, what's your name? USING FGETS\n");
    ptr = fgets(name, MAX, stdin); /* character array, max chars to read, stdin means use keyboard, returns a pointer
                                      solves the problem of gets() not checking length of input. But, the fgets() function
                                      store sthe new line character in the string, causing the weird output of the printf
                                      function below.   */
    printf("%s? Ah! %s!", name, ptr);

    printf("Hi, what's your name? USING SCANF\n");
    scanf("%s", name); /* Takes input up to the first whitespace character or
                                                      The end of file marker (EOF). More of a Get Word function than
                                                      a Get String function.
                                                      scanf will return the number of characters successfully read or
                                                      EOF if it encounters the EOF symbol.   */
    printf("Enter that again, %s. This time I'll take up to the first 5 characters.\n", name);
    scanf("%5s", name);
    printf("Enter that again, %s. This time I'll take up to the first 10 characters.\n", name);
    scanf("%10s", name);
    printf("Thanks, %s\n", name);

    return 0;
}
